services:
  - type: web
    name: sentimentapi-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: sentimentapi-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_URL
        value: https://sentimentapi-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
